#! /bin/bash

# Created By Adarsh Addee
# Aim: To Access Root Privileges in Termux
# Date: 27 Aug 2021
# Note: THIS TOOL IS ONLY FOR LEGAL AND FAIR USE

clear
echo -e "\e[1;31m"

echo "Hit ENTER to continue..."
read

echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp -v bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc
clear

apt-get update && apt-get upgrade -y
apt-get install fish  ncurses-utils proot proot-distro tsu fakeroot parted -y


clear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "
echo -e "\e[1;33m                                 ROOT TERMUX"

echo -e "\e[1;32m"

echo "            YouTube: Gott Modus"
echo "            GitHub: g0dm0de1337"
echo "             insta: g0ttm0dus"
echo -e "\e[1;36m\n"
echo "[*] Automation started"
sleep 0,5
echo "[*] Syncing"
sleep 1
echo "[*] Collecting packages"
sleep 1
echo "[*] Preparing files"
sleep 1
echo "[*] Providing ROOT access"
sleep 1
sleep 1
echo "[*] DONE"

sleep 1.5

echo " "
echo " "
echo -e "USE \e[1;32mfish\e[1;34m later in a new session. Type in the new Shell \e[1;32mroot \e[1;34m"
echo " "
echo " "
echo -e "TYPE NOW \e[1;32mroot \e[1;34m TO ACCESS REAL ROOT PRIVILEGES"
read
echo " "
echo " "
echo " "
echo " "



