#! /bin/bash

# Created By Adarsh Addee Modify By g0dm0de1337
# Aim: To Access Root Privileges in Termux
# Date: 20 Aug 2022
# Note: THIS TOOL IS ONLY FOR LEGAL AND FAIR USE

clear
echo -e "\e[1;31m"

echo "Hit ENTER to continue..."
read

echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp -v bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc
clear

apt-get update && apt-get upgrade -y
apt-get install fish  ncurses-utils proot proot-distro tsu fakeroot parted -y


clear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "
echo -e "\e[1;33m                                 ROOT TERMUX"

echo -e "\e[1;32m"

echo "            YouTube: Gott Modus"
echo "            GitHub: g0dm0de1337"
echo "             insta: g0ttm0dus"
echo -e "\e[1;36m\n"
echo "[*] Automation started"
sleep 0.25
echo "[*] Syncing"
sleep 0.5
echo "[*] Collecting packages"
sleep 0.5
echo "[*] Preparing files"
sleep 0.5
echo "[*] Providing ROOT access"
sleep 0.5
sleep 0.5
echo "[*] DONE"

sleep 2.5
clear
echo " "
echo " "
echo " "
echo " "
echo -e "\e[1;36mRestart Termux & type in your rebooted terminal: \e[1;31mroot"
sleep 3
echo " "
echo " "
echo -e "\e[1;34mUSE the new command \e[1;32mfish\e[1;34m , for a new special shell."
sleep 3
echo " "
echo " "
echo " "
echo -e "\e[1;34mType in your new shell: \e[1;34m\e[1;31mroot \e[1;34mfor FULL ROOT in termux"
sleep 4.5
echo " "
echo " "
echo -e "\e[1;34mUse any key to \e[1;36m"close" \e[1;34mthis script."
read




