#! /bin/bash

# Created By Adarsh Addee
# Aim: To Access Root Privileges in Termux
# Date: 27 Aug 2021
# Note: THIS TOOL IS ONLY FOR LEGAL AND FAIR USE

clear
echo -e "\e[1;31m"

echo "Hit ENTER to continue..."
read

echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp -v bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc
clear

apt-get update && apt-get upgrade -y
apt-get install fish -y
apt-get ncurses-utils proot proot-distro tsu fakeroot parted -y

clear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "
echo -e "\e[1;33m                                 ROOT TERMUX"

echo -e "\e[1;32m"

echo "            YouTube: Gott Modus"
echo "            GitHub: g0dm0de1337"
echo "             insta: g0ttm0dus"
echo -e "\e[1;36m\n"
echo "[*] Automation started"
sleep 1
echo "[*] Syncing"
sleep 2
echo "[*] Collecting packages"
sleep 2
echo "[*] Preparing files"
sleep 2
echo "[*] Providing ROOT access"
sleep 2
sleep 2
echo "[*] DONE"

sleep 1.5

echo " "
echo " "
echo -e "\e[1;34mType \e[1;32mfakeroot\e[1;34m to access fake root privileges"
echo -e "TYPE \e[1;32mroot\e TO ACCESS REAL ROOT PRIVILEGES"
echo -e "USE \e[1;32mfish \e and type in the new shell \e[1;32mroot\e"
read
echo " "
echo " "
echo " "
echo " "



